services:
  sentio:
    build:
      context: ..
      dockerfile: Dockerfile
    # Or use the image from Docker Hub or GitHub Container Registry
    # image: padi2312/sentio:latest
    # image: ghcr.io/p-arndt/sentio:latest
    restart: unless-stopped 
    read_only: true
    mem_limit: 1G
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    restart: unless-stopped 
    read_only: true
    mem_limit: 512M
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
